name: Build and Publish Docker Image
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Verify repository structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Go modules:"
          cat go.mod || true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Update Go modules
        run: |
          echo "Tidying Go modules..."
          go mod tidy
          go mod download
          git diff go.mod go.sum || true
      - name: Build Go binary
        run: |
          echo "Building Go binary..."
          go build -o xbvr -v .
          ls -la xbvr
          file xbvr || true
      - name: Build UI
        run: |
          cd ui
          yarn install --ignore-engines
          yarn build
          cd ..
      - name: Verify build artifacts
        run: |
          echo "Build artifacts:"
          ls -la
          echo "UI build directory:"
          ls -la ./ui/dist/ || true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Show image digest
        run: |
          echo "Image digest: ${{ steps.build_and_push.outputs.digest }}"
